### PR TITLE
Dev

### PR DESCRIPTION
**Pull request by timothyhinea**
Added user stories As an administrator, I can add a student to the system.  I input the student email and name.  The student email must not already exists in the system.
As an administrator, I can put student registration on HOLD.
As an administrator, I can release the HOLD on student registration.
Added J-Unit tests.

### CODE REVIEW

**Comment by timothyhinea** [comment]
@davidsullivan89 can you check this out and let me know what you think?

**Comment by dsullivan89** [comment]
Unfortunately the JUnit test were unable to run. I'm not sure this is user error on my part or the code itself.

**Comment by timothyhinea** [comment]
Hey @dsullivan89 I just fixed the J-unit tests! Please let me know what you think.

**Comment by dsullivan89** [comment]
All issues have been fixed. Code is error free.

**Pull request merged**
